// user et admin
export const TRY_AUTH = "TRY_AUTH";
export const GET_LIST_USER = "GET_LIST_USER";
export const GET_LIST_ADMIN = "GET_LIST_ADMIN";
export const TRY_AUTH_ERROR = "TRY_AUTH_ERROR";
export const TRY_AUTH_ISLOADING = "TRY_AUTH_ISLOADING";
export const DELETE_LIST_ADMIN = " DELETE_LIST_ADMIN";
export const DELETE_LIST_USER = " DELETE_LIST_USER";
export const ADD_LIST_ADMIN = "ADD_LIST_ADMIN";
export const GET_BY_ID_LIST_ADMIN = "GET_BY_ID_LIST_ADMIN";
export const GET_BY_ID_LIST_USER = "GET_BY_ID_LIST_USER";
export const UPDATE_LIST_ADMIN = "UPDATE_LIST_ADMIN";
export const ADD_LIST_USER = "ADD_LIST_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
export const EDIT_ADMIN_SUCCESS = "EDIT_ADMIN_SUCCESS";
// product
export const GET_LIST_PRODUCT = "GET_LIST_PRODUCT";
export const DELETE_LIST_PRODUCT = "DELETE_LIST_PRODUCT";
export const ADD_LIST_PRODUCT = "ADD_LIST_PRODUCT";
export const GET_BY_ID_LIST_PRODUCT = "GET_BY_ID_LIST_PRODUCT ";
export const UPDATE_LIST_PRODUCT = "UPDATE_LIST_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
// pays
export const GET_LIST_COUNTRY = "GET_LIST_COUNTRY";
export const DELETE_LIST_COUNTRY = "DELETE_LIST_COUNTRY";
export const ADD_LIST_COUNTRY = "ADD_LIST_COUNTRY";
export const UPDATE_LIST_COUNTRY = "UPDATE_LIST_COUNTRY";
export const GET_BY_ID_LIST_COUNTRY = "GET_BY_ID_LIST_COUNTRY";
export const EDIT_COUNTRY_SUCCESS = "EDIT_COUNTRY_SUCCESS";
export const ADD_COUNTRY_SUCCESS = "ADD_COUNTRY_SUCCESS";

// affiche kyc
export const GET_INTERNATIONAL_SEARCH = "GET_INTERNATIONAL_SEARCH";
// search
export const GET_LIST_SEARCH = "GET_LIST_SEARCH";
export const DELETE_LIST_SEARCH = "DELETE_LIST_SEARCH";
export const GET_LOCAL_SEARCH = "GET_LOCAL_SEARCH";
export const GET_BY_ID_LIST_SEARCH = "GET_BY_ID_LIST_SEARCH";
export const INTERNATIONAL_SEARCH_IS_LOADING =
  "INTERNATIONAL_SEARCH_IS_LOADING";
// dashboard
export const GET_LIST_DASHBOARD = "GET_LIST_DASHBOARD";
//my account
export const PASSWORD_RESET = "PASSWORD_RESET";
export const SEND_EMAIL = "SEND_EMAIL";
// reset password via email
export const NEW_PASSWORD_RESET = "NEW_PASSWORD_RESET";
//NOTIFICATON
export const GET_NOTIFICATION = "GET_NOTIFICATION";
export const ADD_NOTIFICATION = "ADD_NOTIFICATION";

// ui
export const SET_THEME = "SET_THEME";
// api listing nom
export const GET_NAME_COUNTRY = "GET_NAME_COUNTRY";
export const GET_NAME_PRODUCT = "GET_NAME_PRODUCT";
